.git
.venv
.idea
.DS_Store
.pytest_cache
.ruff_cache
.mypy_cache
**/__pycache__
**/*.py[cod]
**/.env
*.egg-info
.coverage
htmlcov

front
bot
tests
docs

docker/bot
docker/front
docker/nginx
docker/db
docker/minio
docker/app/Dockerfile
docker/app/Dockerfile.dockerignore
docker/app/.env
docker/app/.env.example
